package original.arithmetic;

import org.apache.spark.SparkConf;
import org.apache.spark.api.java.JavaSparkContext;
import org.apache.spark.api.java.JavaPairRDD;
import org.apache.spark.api.java.JavaRDD;
import org.apache.spark.api.java.function.Function2;
import org.apache.spark.api.java.function.PairFlatMapFunction;
import scala.Tuple2;
import java.util.ArrayList;
import java.util.Map;
import java.util.List;

public class MaxAbs {
	
	public static int maxAbsList(List<Integer> data) {
		int max = 0;
		max = Integer.MIN_VALUE;
		{
			int i = 0;
			i = 0;
			boolean loop$0 = false;
			loop$0 = false;
			while (true) {
				if (loop$0) {
					{
						int flat$1 = i + 1;
						i = (int) flat$1;
					}
					;
				}
				int flat$2 = data.size();
				loop$0 = i < flat$2;
				if (loop$0) {
					Integer flat$3 = data.get(i);
					int val = 0;
					val = Math.abs(flat$3);
					boolean flat$4 = max < val;
					if (flat$4) { max = val; }
				} else {
					break;
				}
			}
		}
		return max;
	}
	
	public MaxAbs() { super(); }
}
